Add maps quiz
rusinikita/trainer pull request #20
Opened 2024-08-09 16:05 UTC by mortum5

2024-08-11 13:56 UTC, rusinikita requested changes

2024-08-11 13:56 UTC, rusinikita commented on challenge/files/11_maps.toml
> +    { text = "The map can be used without initialization" },
I think that first question overwhelms. We need to split it.

<img width="972" alt="Screenshot 2024-08-11 at 15 47 57" src="https://github.com/user-attachments/assets/3ff92e5e-d85a-472f-8f4b-7ba6d4a48b42">

### First question.

```go
func main() {
	var m map[int]bool
	
        val, ok := m[1]
	fmt.Println(val, " ", ok)
	
        for i := 0; i < 5; i++ {
		m[i] = i%2 == 0
	}

	fmt.Println(m)
```

What program prints - not compiles, panic, false false, false false and panic

### Fixed initialization questions

Replace code with new snippet with fixed map initialization. 

```go
func main() {
	var m map[int]bool
	fmt.Println(m)
	
        for i := 0; i < 5; i++ {
		m[i] = i%2 == 0
	}

	fmt.Println(m)
```

What program prints. Plus next question - why.

### random order question

```go
func main() {
	var m map[int]bool
	fmt.Println(m)

	val, ok := m[1]
	fmt.Println(val, ok)

	for i := 0; i < 5; i++ {
		m[i] = i%2 == 0
	}

	var toPrint []int
	for key := range m {
		toPrint = append(toPrint, key)
	}

	fmt.Println(toPrint)
}
```

What it prints. Next question - why

### clean question

I think we should skip it.

2024-08-11 13:56 UTC, rusinikita commented on challenge/files/11_maps.toml
> +    { text = "The map can be used without initialization" },
You can change co with question `new_code_snippet` field

<img width="491" alt="Screenshot 2024-08-11 at 16 36 47" src="https://github.com/user-attachments/assets/bf424e65-66db-44f7-8662-0528919a0598">

2024-08-11 13:56 UTC, rusinikita commented on challenge/files/11_maps.toml
> +    { text = "The hash function includes a per-map random seed to protect against certain types of attacks", code_line_ranges = [] },
Let's specify the attack name and add proof in the learning links. I don't know about it and want to read)

2024-08-12 16:05 UTC, mortum5 commented on challenge/files/11_maps.toml
> +    { text = "The hash function includes a per-map random seed to protect against certain types of attacks", code_line_ranges = [] },
it's not like there's some famous attack using this. I just took it from what I read on a blog. Here's a link, but it's not an official document. I can remove this question.

[Link to Hackernoon](https://hackernoon.com/some-insights-on-maps-in-golang-rm5v3ywh#:~:text=I%20think%2C%20the%20idea%20behind%20this%20randomization%20is%20to%20avoid%20potential%20vulnerabilities%20when%20malicious%20actor%20will%20flood%20hashmap%20with%20collisions%20and%20to%20prevent%20any%20attempts%20to%20rely%20on%20map%20iteration%20order.%20Map%20is%20iterable%2C%20but%20not%20ordered.%20Even%20every%20new%20iterator%20of%20the%20same%20map%20is%20randomized)

2024-08-15 16:44 UTC, rusinikita requested changes

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +“Learning is never done without error, and defeat ” – Vladimir Lenin.
Test data. Let's write something useful

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +    { text = "Iteration over map keys is randomized between every for range call", code_line_ranges = [] },
Can't understand "between every for range call"

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +text = """What happens when the number of entries in a Go map exceeds a certain threshold?
Don't understand "certain threshold"

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +Which of the following best describes the load factor in the context of Go maps?
Maybe this question needs to be before "What happens when"

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +    { text = "The hash function includes a per-map random seed to protect against certain types of attacks", code_line_ranges = [] },
Let's specify "attack when malicious actor will flood hashmap with collisions"

And let's add link in useful links

Once, I was asked about bucket overflow (or something like that) when the attacker tries to find keys to overflow only a single bucket it makes service significantly slower.

2024-08-15 16:44 UTC, rusinikita commented on challenge/files/11_maps.toml
> +
We need to add the question "What happens when we need to add new value, but the bucket is full"

2024-09-14 18:43 UTC, rusinikita approved these changes

2024-09-14 18:43 UTC, merged